### PR TITLE
Improve customizability

### PR DESCRIPTION
**Pull request by JoakimLofgren**
This enables a user to copy `hack/ui` into a separate repo and customize the UI.

If you like these changes I can update the README with some instructions on how to customize the UI.

### CODE REVIEW

**Comment by amdonov** [comment]
I'm not against these changes if they make it easier for you use lite-idp. UI is an interface, so you could just specify an alternative implementation for those changes. I didn't have time to look at it just now, but it looks like the build of this failed. If you get that resolved, I'll merge it.

**Comment by JoakimLofgren** [comment]
Seems to have been something with the "tip" version of go lang.
I specified 1.12.x and it seems to work.

**Comment by JoakimLofgren** [comment]
@amdonov Tried to find a new version of the docker image.

https://quay.io/repository/amdonov/lite-idp?tab=info Seems to show some failures?
But I can't see what is going wrong.

I had to make some changes to the Dockerfile to make it build with `docker build .` locally.

```
± git diff --patch
diff --git a/Dockerfile b/Dockerfile
index e851140..fa8c14d 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,7 +1,10 @@
 FROM golang:1-alpine
 
+RUN apk add git
+
 COPY . /go/src/github.com/amdonov/lite-idp
 WORKDIR /go/src/github.com/amdonov/lite-idp
+RUN go get .
 RUN go build .
 
 FROM alpine
```

Want me to make a PR with that change as well?

**Comment by amdonov** [comment]
I'm working to vendor those dependencies. They came in as part of a merge
request.

**Comment by amdonov** [comment]
You should be all set. Thanks for letting me know about the images.

**Comment by JoakimLofgren** [comment]
`docker pull quay.io/amdonov/lite-idp` is preferred over `docker pull amdonov/lite-idp` ?

The docker hub doesn't seem to be updated?

**Comment by amdonov** [comment]
Yes

**Pull request merged**
